corretto:
  plugins:
    - module: corretto.plugins.MathTable
    - module: corretto.plugins.MergeTTX
    - module: corretto.plugins.FixedPitch
    - module: corretto.plugins.GaspTable
    - module: corretto.plugins.DeltaBase
    - module: corretto.plugins.MaxpStack
    - module: corretto.plugins.HeadTable
    - module: corretto.plugins.VariableFontMetrics
    - module: corretto.plugins.Save
    - module: corretto.plugins.SaveTTX
    - module: corretto.plugins.Webfonts
    - module: CorrettoSubsetter
